name: tattoo_flutter
description: 'A new Flutter module project.'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

  module:
    androidX: true
    androidPackage: com.example.tattoo_flutter
    iosBundleIdentifier: com.example.tattooFlutter
