name: tattoo_flutter
description: 'A new Flutter module project.'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.15
  intl: ^0.19.0
  flutter_debouncer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

  module:
    androidX: true
    androidPackage: com.example.tattoo_flutter
    iosBundleIdentifier: com.example.tattooFlutter
